FROM oven/bun:1

ENV DATABASE_URL=${DATABASE_URL}
ENV CORS_ORIGIN=${CORS_ORIGIN}
ENV JWT_SECRET=${JWT_SECRET}
ENV PORT=8000

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install

RUN bun run generate:db

EXPOSE 8000

CMD ["bun", "start:backend"]