FROM oven/bun:1

ENV HTTP_BACKEND_URL=${HTTP_BACKEND_URL}
ENV NEXT_PUBLIC_HTTP_BACKEND_URL=${NEXT_PUBLIC_HTTP_BACKEND_URL}
ENV NEXT_PUBLIC_AUTH_SECRET=${NEXT_PUBLIC_AUTH_SECRET}

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN bun install

RUN bunx turbo build

EXPOSE 3000

CMD ["bun", "start:frontend"]
