name: Continuous Deployment (Backend)
on:
    push:
      branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v2

            # Docker login
            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            # Build and push the image
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: souravbhowal/taskapp_backend:${{ github.sha }}
                    

            # SSH into the server and pull the image and run the container
            - name: SSH into the server and pull the image and run the container
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                passphrase: ${{ secrets.SSH_PASSPHRASE }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    docker stop taskapp_backend
                    docker rm taskapp_backend
                    docker pull souravbhowal/taskapp_backend:${{ github.sha }}
                    docker run --name taskapp_backend -d \
                        -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                        -e CORS_ORIGIN=${{ secrets.CORS_ORIGIN }} \
                        -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                        -e PORT=8000 \
                        -p 8000:8000 \
                        souravbhowal/taskapp_backend:${{ github.sha }}