name: Continuous Deployment (Frontend)
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: souravbhowal/taskapp_frontend:${{ github.sha }}
          
      # SSH into the server and pull the image and run the container
      - name: SSH into the server and pull the image and run the container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop taskapp_frontend
            docker rm taskapp_frontend
            docker pull souravbhowal/taskapp_frontend:${{ github.sha }}
            docker run --name taskapp_frontend -d \
                -e HTTP_BACKEND_URL=${{ secrets.HTTP_BACKEND_URL }} \
                -e NEXT_PUBLIC_HTTP_BACKEND_URL=${{ secrets.NEXT_PUBLIC_HTTP_BACKEND_URL }} \
                -e NEXT_PUBLIC_AUTH_SECRET=${{ secrets.NEXT_PUBLIC_AUTH_SECRET }} \
                -e AUTH_URL=${{ secrets.AUTH_URL }} \
                -p 3000:3000 \
                souravbhowal/taskapp_frontend:${{ github.sha }}

      